// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeWxaMz5NlvobbBWazhnXN9omKGLU9ix8',
    appId: '1:466521997950:web:40b6932ed809f23b000e2f',
    messagingSenderId: '466521997950',
    projectId: 'chatapptute-26fb7',
    authDomain: 'chatapptute-26fb7.firebaseapp.com',
    databaseURL: 'https://chatapptute-26fb7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapptute-26fb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTop5Gv6AwqZi7Y4LL_7Mb8cgqSBRI9hs',
    appId: '1:466521997950:android:4e372400075cbc35000e2f',
    messagingSenderId: '466521997950',
    projectId: 'chatapptute-26fb7',
    databaseURL: 'https://chatapptute-26fb7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapptute-26fb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ewK93tVskQZobtO-RoB-7o2V995ATgo',
    appId: '1:466521997950:ios:3bb9181365fedce8000e2f',
    messagingSenderId: '466521997950',
    projectId: 'chatapptute-26fb7',
    databaseURL: 'https://chatapptute-26fb7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapptute-26fb7.appspot.com',
    iosClientId: '466521997950-p3mehjuarqvcvmtkd92tpo3qtalrts8t.apps.googleusercontent.com',
    iosBundleId: 'com.arnavdham.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ewK93tVskQZobtO-RoB-7o2V995ATgo',
    appId: '1:466521997950:ios:d8e2f10d0e92e616000e2f',
    messagingSenderId: '466521997950',
    projectId: 'chatapptute-26fb7',
    databaseURL: 'https://chatapptute-26fb7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatapptute-26fb7.appspot.com',
    iosClientId: '466521997950-1m31sv2fc2km8es17obuann66ml3no0u.apps.googleusercontent.com',
    iosBundleId: 'com.arnavdham.chatapp.RunnerTests',
  );
}
